# Generated by Django 4.0.4 on 2022-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
